import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/shared";
import localFont from "next/font/local";

const PTRootUI = localFont({
  src: [
    {
      path: "./fonts/PTRootUI-Regular.woff2",
      weight: "400",
    },
    {
      path: "./fonts/PTRootUI-Medium.woff2",
      weight: "500",
    },
    {
      path: "./fonts/PTRootUI-Bold.woff2",
      weight: "700",
    },
  ],
});

const robotoFont = Roboto({
  weight: ["400", "500", "700", "900"],
  style: ["normal"],
  subsets: ["latin", "cyrillic"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Tanuki",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${PTRootUI.className} antialiased`}>
        <main className="min-h=screen">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
